services:
  datacollector-rc:
    image: eersaa/iot-mini-project:rc-datacollector
    ports: 
      - 5683

  acceptance-tests:
    image: eersaa/iot-mini-project:latest-acceptance-tests
    depends_on:
      - datacollector-rc
