services:
  datacollector-rc:
    image: eersaa/iot-mini-project:rc-datacollector
    ports: 
      - 8683:8683/udp
    networks:
      - ipv6-network

  acceptance-tests:
    image: eersaa/iot-mini-project:latest-acceptance-tests
    depends_on:
      - datacollector-rc
    networks:
      - ipv6-network

networks:
  ipv6-network:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fc00::/112