name: continuous delivery

on: [push]

jobs:
  build_unit_tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build image for all unit tests
      run: | 
            docker build --file ${{ github.workspace }}/Dockerfile \
                        --target unit-tests \
                        --tag ${{ secrets.DOCKERHUB_USERNAME }}/unit-tests:latest \
                        ${{ github.workspace }}/cloud

  build_acceptance_tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build image for all acceptance tests
      run: | 
            docker build --file ${{ github.workspace }}/Dockerfile \
                        --target acceptance-tests \
                        --tag ${{ secrets.DOCKERHUB_USERNAME }}/acceptance-tests:latest \
                        ${{ github.workspace }}/cloud

  run_commit_tests:
    runs-on: ubuntu-22.04
    needs: build_unit_tests

    steps:
    - name: Run all unit tests
      run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/unit-tests:latest

  run_acceptance_tests:
    runs-on: ubuntu-22.04
    needs: run_commit_tests

    steps:
    - name: Run all unit tests
      run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/acceptance-tests:latest
