name: continuous delivery

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
# Build application images
    - name: Build image for datacollector unit tests
      run: | 
            docker build --target test-env \
                        --tag ${{ secrets.DOCKERHUB_USERNAME }}/datacollector-test:latest \
                        ./iot_mini_project/datacollector
# Run commit tests
    - name: Run datacollector unit tests
      run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/datacollector-test:latest

# Build acceptance tests image
    - name: Build acceptance tests Docker image
      run: |
            docker build --target acceptance-tests \
                        --tag ${{ secrets.DOCKERHUB_USERNAME }}/acceptance-test:latest \
                        .

# Deploy application
# Run acceptance tests
    - name: Run acceptance tests
      run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/acceptance-test:latest
